### ISSUE TITLE
Execute minimum amount validation after providing the value

### ISSUE THREAD

**Issue by nkuba** [thesis/acre#774]
We recently updated the validation on the deposit form to run on the form submitted instead of after entering the amount.
This leads to the following:
- when a user enters an amount more than the minimum deposit amount >=0.015, the fees are calculated correctly
- when a user enters an amount less than the minimum deposit <0.015 the fees are not calculated, and no information is displayed until they hit the submit button.

We still don't want to calculate the fees if the amount is below the minimum deposit threshold, but we need to show the validation error before the user submits the form.

In this task we need to update the form validation for the minimum amount, so the error is shown after the user enters the value and leaves the input field for both Deposit and Withdraw form.

**Comment by nkuba** [comment]
@kpyszkowski, could you please confirm whether this issue was covered by https://github.com/thesis/acre/pull/790 ? If so, please close it :)

**Comment by kpyszkowski** [comment]
@nkuba 
I researched it. All remarks applies exactly the same both to deposit and withdrawal flows (skipping the minimum amount).

1. When a user enters an amount more than the minimum deposit amount >=0.015, the fees are calculated correctly: ✅ 
2. When a user enters an amount less than the minimum deposit <0.015 the fees are not calculated: ✅ 
3. (...) And no information is displayed until they hit the submit button: 🚫 
When user takes the focus out of the amount field, the validation is triggered and the error message about minimum deposit amount is displayed. User is unable to hit the submit button since it's disabled until the validation passes. Fees remain zeroed. This is fine in terms of UX in my opinion. 

The only flaw that grabs my attention is the fact that we calculate points even when the minimum deposit amount requirement is not fulfilled. It looks kinda awkward to me when fees are zeroed but points amount is presented. Don't you think we should zero it as well until the minimum deposit amount requirement is met? 

<img width="565" alt="image" src="https://github.com/user-attachments/assets/ea4c0435-261f-4e57-b9ff-4f81b820eb02">

**Comment by nkuba** [comment]
Thanks @kpyszkowski! I'm closing this issue, then.
Good finding with the points amount calculation - I added it to our backlog (https://github.com/thesis/acre/issues/829).
