### ISSUE TITLE
[UI] Change Request: Update Wallet Connection Modal Design

### ISSUE THREAD

**Issue by SorinQ** [thesis/acre#870]
Description

Update the wallet connection modal behavior to treat modal closure as info instead of an error and replace the displayed text.

Current Behavior

- Modal closure is currently treated as an error.

Requested Change

- Change the design to treat modal closure as info.
- Update the displayed message.
    
Figma:
https://www.figma.com/design/Ov4M1oVlSrO4Pl7NmGOHC1/Ledger-2025?node-id=780-1267&t=9RPMRF8Lyi4jPTg2-4

**Comment by michalinacienciala** [comment]
@SorinQ, just to clarify - is the expected behavior to:
A) Change the text to less punitive on `Select your account` window for all interactions when user closes the `CHOOSE ACCOUNT` LL window (no matter if in logged-in or logged-out state)?
B) Change the text to less punitive on `Select your account` window when user closes the `CHOOSE ACCOUNT` LL window while in logged-out state. Close the `Select your account` window when user closes the `CHOOSE ACCOUNT` LL window while in logged-in state.
